# HW3

## 1 
Read the code below and rewrite it using only numpy functions (without for loop, if-else statements). Benchmark your implementation. How much is it faster than the naive python implementation? (hint: use np.isin)

def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx

In [4]:
def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx

import numpy as np

def func2(names, db):
    return np.arange(len(db))[np.isin(db,names)]

In [5]:
names = range(1000)
db = range(99999)

In [6]:
%time result1 = func1(names,db)

CPU times: user 524 µs, sys: 45 µs, total: 569 µs
Wall time: 601 µs


In [7]:
%time result2 = func2(names,db)

CPU times: user 19.6 ms, sys: 5.94 ms, total: 25.6 ms
Wall time: 27.5 ms


## 2
Use only numpy functions (without for loop, if-else statements) to find the largest 3 distances between points if either points is inside the circle of raidus r0. Then return these points. E.g.

In [74]:
def search_pairs(A, r):
    #calculate the distance of each point from (0,0)
    dis_from_0 = np.sqrt(np.square(A[:,0])+np.square(A[:,1]))
    #select the points that are inside the circle of radius r
    mask = np.where(dis_from_0 < r,True,False)
    A_new = A[mask]
    #calculate the distance of each pair of points
    B = A_new.copy().transpose()
    A_mul_BT = np.dot(A_new,B)
    A_square = np.square(A_new[:,0])+np.square(A_new[:,1])
    A_square_reshaped = np.tile(A_square.transpose(), (1, A_mul_BT.shape[1])).reshape(3,3)
    A_square_reshaped_T = A_square_reshaped.transpose()
    distance_each_pair = A_square_reshaped + A_square_reshaped_T - 2*A_mul_BT 
    return distance_each_pair

coordinates = np.array(
[[0.968, 0.313],
 [0.692, 0.876],
 [0.895, 0.085],
 [0.039, 0.17 ],
 [0.878, 0.098]]
)
cirle_r0 = 0.9
print(search_pairs(coordinates, cirle_r0))

[[0.00000000e+00 7.39961000e-01 4.58000000e-04]
 [7.39961000e-01 6.93889390e-18 7.09105000e-01]
 [4.58000000e-04 7.09105000e-01 2.22044605e-16]]
